name: setup-zig

description: Install Zig using cache if available.

inputs:
  version:
    required: true
    description: The version of Zig to install.

runs:
  using: composite
  steps:
      - uses: actions/cache@v5
        with:
          path: ~/.zig
          key: zig-x86_64-linux-${{inputs.version}}

      - name: Install zig
        shell: bash
        run: |
          if [ ! -d ~/.zig/zig-x86_64-linux-${{inputs.version}} ]; then
            curl https://ziglang.org/download/${{inputs.version}}/zig-x86_64-linux-${{inputs.version}}.tar.xz -L -o zig.tar.xz
            tar -xf zig.tar.xz -C ~/.zig
          fi
          echo "$(realpath ~/.zig/zig-x86_64-linux-${{inputs.version}})" >> $GITHUB_PATH
