//! mkfont: Generate a font data from a text file containing ASCII font representation.
//!
//! #### Font file format
//!
//! <width>,<height>,<total>
//!
//! <code>
//! <glyph data line 1>
//! ...
//! <glyph data line N>
//!
//! <code>
//! ...
//!

const Options = enum {
    /// Output file path.
    output,
    /// Input font file path.
    input,
};

/// Options map.
const optmap = std.StaticStringMap(Options).initComptime(&.{
    .{ "--output", .output },
    .{ "--input", .input },
});

/// Print a usage and exit.
fn usage(logger: anytype) noreturn {
    logger("Usage: mkfont <options...>", .{});
    logger(
        \\Options:
        \\  --output <path>     Path to output file (required)
        \\  --input  <path>     Path to input font text file (required)
    ,
        .{},
    );

    std.process.exit(1);
}

/// Command line arguments.
const Args = struct {
    output: ?std.Io.File = null,
    input: ?std.Io.File = null,
};

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const allocator = init.gpa;
    var args = Args{};
    var argiter = init.minimal.args.iterate();
    defer argiter.deinit();
    _ = argiter.next(); // Skip the program name.

    // Open CWD.
    var cwd_buf: [128]u8 = undefined;
    const cwd_path = cwd_buf[0..try std.process.currentPath(init.io, &cwd_buf)];
    const cwd = try std.Io.Dir.openDirAbsolute(init.io, cwd_path, .{});
    defer cwd.close(init.io);

    // Parse arguments.
    while (argiter.next()) |arg| {
        switch (optmap.get(arg) orelse usage(log.err)) {
            .output => {
                const path = argiter.next() orelse usage(log.err);
                args.output = try cwd.createFile(io, path, .{});
            },
            .input => {
                const path = argiter.next() orelse usage(log.err);
                args.input = try cwd.openFile(io, path, .{});
            },
        }
    }
    if (args.output == null or args.input == null) {
        usage(log.err);
    }

    // Create a font file reader.
    var rbuf: [4096]u8 = undefined;
    var reader = args.input.?.reader(io, &rbuf);
    var fr = try FontReader.init(&reader.interface, allocator);

    // Create a writer for output Zig file.
    var wbuf: [4096]u8 = undefined;
    var writer = args.output.?.writer(io, &wbuf);

    // Create a Zig output composer and generate the output.
    var composer = Composer.init(&fr);
    try composer.compose(&writer.interface);

    while (try fr.next()) |font| {
        defer font.deinit();
    }
    try writer.flush();
}

/// Zig file writer for the generated font data.
const Composer = struct {
    /// Font reader.
    reader: *FontReader,

    const Self = @This();

    pub fn init(reader: *FontReader) Self {
        return .{ .reader = reader };
    }

    pub fn compose(self: *Self, writer: *std.Io.Writer) !void {
        try self.writeHeader(writer);

        while (try self.reader.next()) |font| {
            defer font.deinit();
            try self.writeFont(font, writer);
        }

        try self.writeFooter(writer);
    }

    fn writeHeader(self: *Self, writer: *std.Io.Writer) !void {
        // Add doc-comment.
        try writer.print(
            \\//! {d}x{d} font bitmap.
            \\//!
            \\//! This file is auto-generated by mkfont tool. Do NOT edit manually.
            \\
            \\
        , .{
            self.reader.width,
            self.reader.height,
        });

        // Add const declarations.
        const num_line_bytes = try std.math.divCeil(usize, self.reader.width, 8);
        try writer.print(
            \\pub const glyph_width: u32 = {};
            \\pub const glyph_height: u32 = {};
            \\pub const num_glyphs: usize = {};
            \\pub const num_line_bytes: usize = {};
            \\
            \\
        , .{
            self.reader.width,
            self.reader.height,
            self.reader.total,
            num_line_bytes,
        });

        // Add font data array declaration.
        try writer.print(
            \\pub const glyphs: [num_glyphs][glyph_height][num_line_bytes]u8 = .{{
            \\
        , .{});
    }

    fn writeFooter(_: *Self, writer: *std.Io.Writer) !void {
        try writer.print(
            \\}};
            \\
        , .{});
    }

    fn writeFont(self: *Self, font: FontIr, writer: *std.Io.Writer) !void {
        try writer.print(
            \\    // 0x{X:0>2}
            \\    .{{
            \\
        , .{font.code});

        for (font.data) |row| {
            try writer.print(
                \\        .{{
            , .{});

            // Write font data.
            for (row, 0..) |byte, i| {
                try writer.print(
                    \\0x{X:0>2}
                , .{byte});

                if (i != row.len - 1) {
                    try writer.print(
                        \\, 
                    , .{});
                } else {
                    try writer.print(
                        \\}}, 
                    , .{});
                }
            }

            // Write comment.
            var comment: [256]u8 = undefined;
            for (row, 0..) |byte, i| {
                _ = try std.fmt.bufPrint(comment[i * 8 ..], "{b:0>8}", .{byte});
            }
            try writer.print(
                \\// {s}
                \\
            , .{comment[0..self.reader.width]});
        }

        try writer.print(
            \\    }},
            \\
        , .{});
    }
};

/// Character representing a zero bit in the input font text file.
const zero_sign = '.';
/// Character representing a one bit in the input font text file.
const one_sign = '@';

/// Font file reader.
const FontReader = struct {
    /// Width of the single character glyph in pixels.
    width: usize,
    /// Height of the single character glyph in pixels.
    height: usize,
    /// Total number of characters in the font.
    total: usize,

    /// Font file reader.
    reader: *std.Io.Reader,
    /// Memory allocator.
    allocator: Allocator,

    const Self = @This();

    pub fn init(reader: *std.Io.Reader, allocator: Allocator) !Self {
        var wbuf: [256]u8 = undefined;
        var writer = std.Io.Writer.fixed(&wbuf);

        // Read the first line containing font metadata.
        const length = try reader.streamDelimiter(&writer, '\n');
        const line = wbuf[0..length];

        // Obtain font metadata from the first line.
        var iter = std.mem.splitAny(u8, line, ",");
        const width = iter.next() orelse return error.InvalidFontFormat;
        const height = iter.next() orelse return error.InvalidFontFormat;
        const total = iter.next() orelse return error.InvalidFontFormat;
        if (iter.peek() != null) return error.InvalidFontFormat;

        return .{
            .width = try std.fmt.parseInt(usize, width, 0),
            .height = try std.fmt.parseInt(usize, height, 0),
            .total = try std.fmt.parseInt(usize, total, 0),
            .reader = reader,
            .allocator = allocator,
        };
    }

    /// Get a next font for a code point.
    ///
    /// Returns null if there is no more font data.
    pub fn next(self: *Self) !?FontIr {
        var al = std.Io.Writer.Allocating.init(self.allocator);
        defer al.deinit();
        const writer = &al.writer;

        var ir = std.ArrayList([]const u8).empty;
        defer ir.deinit(self.allocator);
        errdefer for (ir.items) |row| self.allocator.free(row);
        var code: u32 = 0;
        var rows: u32 = 0;
        var state: enum { code, data } = .code;

        while (self.reader.streamDelimiter(writer, '\n')) |length| {
            // Discard newline character.
            self.reader.toss(1);

            // Ignore empty lines.
            if (length == 0) continue;

            const line = try al.toOwnedSlice();
            defer self.allocator.free(line);

            switch (state) {
                .code => {
                    code = try std.fmt.parseInt(u32, line, 0);
                    state = .data;
                },
                .data => {
                    const data = try parseLine(line, self.width, self.allocator);
                    errdefer self.allocator.free(data);
                    try ir.append(self.allocator, data);
                    rows += 1;
                },
            }

            if (rows == self.height) {
                break;
            }
        } else |err| switch (err) {
            error.EndOfStream => {},
            else => return err,
        }

        if (state == .code) {
            // No more font data.
            return null;
        }
        if (rows != self.height) {
            return error.InvalidFontFormat;
        }

        return .{
            .code = code,
            .data = try ir.toOwnedSlice(self.allocator),
            .allocator = self.allocator,
        };
    }
};

/// Parse a line of the font data and convert it to a byte array.
fn parseLine(line: []const u8, width: usize, allocator: Allocator) !FontLine {
    if (line.len != width) {
        return error.InvalidFontFormat;
    }

    var result = std.ArrayList(u8).empty;
    defer result.deinit(allocator);

    var value: u8 = 0;
    for (line, 0..) |c, i| {
        if (c == zero_sign) {
            value <<= 1;
        } else if (c == one_sign) {
            value = (value << 1) | 1;
        } else {
            return error.InvalidFontFormat;
        }

        if ((i + 1) % 8 == 0) {
            try result.append(allocator, value);
            value = 0;
        }
    }

    if (width % 8 != 0) {
        value <<= @intCast((8 - (width % 8)));
        try result.append(allocator, value);
    }

    return result.toOwnedSlice(allocator);
}

/// Represents a line of the font data.
///
/// If the width is not a multiple of 8, the remaining bits in the last byte are ignored.
const FontLine = []const u8;

/// Intermediate representation of the font data.
const FontIr = struct {
    /// Font code.
    code: u32,
    /// Font data.
    data: []FontLine,
    /// Allocator that owns the font data.
    allocator: Allocator,

    pub fn deinit(self: FontIr) void {
        for (self.data) |row| {
            self.allocator.free(row);
        }
        self.allocator.free(self.data);
    }
};

// =============================================================
// Imports
// =============================================================

const std = @import("std");
const log = std.log;
const os = std.os;
const Allocator = std.mem.Allocator;
const ArrayList = std.ArrayList;
