name: Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  ZIG_VERSION: 0.16.0

jobs:
  lint:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Lint Zig
        run: |
          zig fmt --check **/*.zig --exclude .zig-cache/**/*.zig

      - name: Spell Check
        uses: crate-ci/typos@v1.29.5
        with:
          files: .github/** urthr/** wyrd/** tools/** *.zig *.zig.zon *.md
          config: _typos.toml
